language: ruby
rvm:
  - 2.4.0
before_install:
  - cp config/database.yml config/database.yml.example
  - cp config/secrets.yml config/secrets.yml.example
  - npm install eslint --save-dev
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:create test
script:
  - RAILS_ENV=test bundle exec rails --trace db:migrate
  - bin/test
addons:
  code_climate:
    repo_token: b5c170c1afddc9215d8ff5831d10afaf4349fbe5f5df8eec750ff0e5c6410725
