language: ruby
rvm:
  - 2.4.0
env:
  - TRAVIS_NODE_VERSION="4"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm install -g eslint
  - bundle install --jobs=3 --retry=3 --deployment
before_install:
  - cp config/database.yml config/database.yml.example
  - cp config/secrets.yml config/secrets.yml.example
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:create test
script:
  - RAILS_ENV=test bundle exec rails --trace db:migrate
  - bin/test
addons:
  code_climate:
    repo_token: b5c170c1afddc9215d8ff5831d10afaf4349fbe5f5df8eec750ff0e5c6410725
