language: ruby
rvm:
  - 2.3.0
before_install:
  - cp config/database.yml config/database.yml.example
  - cp config/secrets.yml config/secrets.yml.example
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:create test
