Course.create(subject: 'CSC', course: 101, title: 'Personal Productivity Software')
Course.create(subject: 'CSC', course: 120, title: 'Problem Solving and Programming Constructs')
Course.create(subject: 'CSC', course: 124, title: 'Computer Programming I')
Course.create(subject: 'CSC', course: 201, title: 'Internet Concepts')
Course.create(subject: 'CSC', course: 265, title: 'Object Oriented Programming')
Course.create(subject: 'CSC', course: 302, title: 'Visual Programming')
Course.create(subject: 'CSC', course: 323, title: 'Assembly Language Programming')
Course.create(subject: 'CSC', course: 328, title: 'Data Structures')
Course.create(subject: 'CSC', course: 400, title: 'Operating Systems')
Course.create(subject: 'CSC', course: 419, title: 'Internship')
Course.create(subject: 'CSC', course: 455, title: 'Structures of Programming Languages')
Course.create(subject: 'CSC', course: 460, title: 'Language Translation')
Course.create(subject: 'CSC', course: 492, title: 'Senior Project II')
Course.create(subject: 'CSC', course: 216, title: 'Logic and Switching Theory')
Course.create(subject: 'CSC', course: 304, title: 'COBOL')
Course.create(subject: 'CSC', course: 306, title: 'FORTRAN')
Course.create(subject: 'CET', course: 350, title: 'Technical Computing using Java')
Course.create(subject: 'CSC', course: 360, title: 'Analysis of Algorithms')
Course.create(subject: 'CSC', course: 378, title: 'Computer Architecture')
Course.create(subject: 'CSC', course: 475, title: 'Theory of Languages')
Course.create(subject: 'CSC', course: 490, title: 'Senior Project I')
Course.create(subject: 'MAT', course: 195, title: 'Discrete Structures')
Course.create(subject: 'MAT', course: 282, title: 'Calculus II')
Course.create(subject: 'MAT', course: 341, title: 'Linear Algebra I')
Course.create(subject: 'MAT', course: 281, title: 'Calculus I')
Course.create(subject: 'MAT', course: 215, title: 'Statistics')
Course.create(subject: 'ENG', course: 217, title: 'Scientific and Technical Writing I')
Course.create(subject: 'ENG', course: 101, title: 'English Composition I')
Course.create(subject: 'ENG', course: 102, title: 'English Composition II')
Course.create(subject: 'CIS', course: 321, title: 'Data Base Management Systems and DB Design')
Course.create(subject: 'CSC', course: 420, title: 'Artificial Intelligence')
Course.create(subject: 'CSC', course: 424, title: 'Numerical Analysis')
Course.create(subject: 'CSC', course: 485, title: 'Special Topics in Computer Science')
Course.create(subject: 'CET', course: 440, title: 'Computer Networking', credits: 4)
Course.create(subject: 'UNI', course: 100, title: 'First Year Seminar', credits: 1)
Course.create(subject: 'HON', course: 100, title: 'Honors & University Orientation', credits: 1)
Course.create(subject: 'CIS', course: 352, title: 'Global, Economic and Social Ethical Issues in Computing')
Course.create(subject: 'MAT', course: 381, title: 'Calculus III')
Course.create(subject: 'MAT', course: 441, title: 'Linear Algebra II')
Course.create(subject: 'COM', course: 101, title: 'Oral Communication')
Course.create(subject: 'MAT', course: 382, title: 'Calculus IV')
Course.create(subject: 'COM', course: 230, title: 'Argument/Debate')
Course.create(subject: 'COM', course: 250, title: 'Oral Com Management')
Course.create(subject: 'MAT', course: 181, title: 'College Algebra')
Course.create(subject: 'ATE', course: 340, title: 'Sports Nutrition')
Course.create(subject: 'BIO', course: 112, title: 'Bio Sex Tr Dis')
Course.create(subject: 'DAN', course: 260, title: 'Modern Dance')
Course.create(subject: 'HSC', course: 115, title: 'Cur Iss Health')
Course.create(subject: 'HSC', course: 250, title: 'Hth/Phy Ed Meth')
Course.create(subject: 'HSC', course: 315, title: 'Fst Aid/Per Safe')
Course.create(subject: 'NUR', course: 101, title: 'Women Health')
Course.create(subject: 'PSY', course: 222, title: 'Psy Stress Mgt')
Course.create(subject: 'REC', course: 165, title: 'Intro Rec Leis')
Course.create(subject: "CHE", course: 101, title: "General Chemistry I", credits: 4)
Course.create(subject: "CHE", course: 102, title: "General Chemistry II", credits: 4)
Course.create(subject: "CHE", course: 331, title: "Organic Chemistry I", credits: 4)
Course.create(subject: "PHY", course: 101, title: "College Physics I", credits: 4)
Course.create(subject: "PHY", course: 202, title: "College Physics II", credits: 4)
Course.create(subject: "PHY", course: 203, title: "College Physics III", credits: 4)
Course.create(subject: "BIO", course: 120, title: "General Zoology", credits: 4)
Course.create(subject: "BIO", course: 125, title: "General Botany", credits: 4)
Course.create(subject: "BIO", course: 215, title: "Basic Microbiology", credits: 4)
Course.create(subject: "PHY", course: 321, title: "Intermediate Electricity and  Magnetism", credits: 4)
Course.create(subject: "BIO", course: 488, title: "Water Pollution Biology", credits: 4)
Course.create(subject: "BIO", course: 445, title: "Entomology", credits: 4)
Course.create(subject: "BIO", course: 248, title: "General Ecology", credits: 4)
Course.create(subject: "BIO", course: 305, title: "Comparative Vertebrate Anatomy", credits: 4)
Course.create(subject: "BIO", course: 306, title: "Human Anatomy", credits: 4)
Course.create(subject: "BIO", course: 325, title: "Animal Histology", credits: 4)
Course.create(subject: "BIO", course: 327, title: "Parasitology", credits: 4)
Course.create(subject: "BIO", course: 328, title: "Human Physiology", credits: 4)
Course.create(subject: "BIO", course: 433, title: "Herpetology", credits: 4)
Course.create(subject: "BIO", course: 486, title: "Comparative Animal Physiology", credits: 4)
Course.create(subject: "EAS", course: 150, title: "Introduction to Geology", credits: 4)
Course.create(subject: "EAS", course: 240, title: "Introduction to Meteorology", credits: 4)
Course.create(subject: 'CMD', course: 350, title: "Sign/Braille I")
Course.create(subject: 'COM', course: 351, title: "Rhet: His/The/Cr")
Course.create(subject: 'ENG', course: 106, title: "Intro to Poetry")
Course.create(subject: 'ENG', course: 107, title: "Intro to Fiction")
Course.create(subject: 'ENG', course: 108, title: "Intro to Drama")
Course.create(subject: 'ENG', course: 112, title: "Myth, Magic, Mys")
Course.create(subject: 'ENG', course: 127, title: "Woman as Hero")
Course.create(subject: 'ENG', course: 148, title: "Horror in Lit")
Course.create(subject: 'ENG', course: 178, title: "Lit and Film")
Course.create(subject: 'ENG', course: 205, title: "Wld Lit to 1600")
Course.create(subject: 'ENG', course: 206, title: "Wld Lit after 1600")
Course.create(subject: 'ENG', course: 301, title: "English Lit I")
Course.create(subject: 'ENG', course: 306, title: "Press/Law/Eth")
Course.create(subject: 'ENG', course: 315, title: "Sur/American Wom")
Course.create(subject: 'ENG', course: 337, title: "Sur/American Lit I")
Course.create(subject: 'ENG', course: 354, title: "Amer Journalism")
Course.create(subject: 'ENG', course: 487, title: "Amer Lit Genres")
Course.create(subject: 'ESP', course: 100, title: "Disab/Pop Med")
Course.create(subject: 'ESP', course: 210, title: "Sp Ed Found/Col")
Course.create(subject: 'FRE', course: 101, title: "Elem French I")
Course.create(subject: 'FRE', course: 102, title: "Elem French II")
Course.create(subject: 'FRE', course: 203, title: "Inter French I")
Course.create(subject: 'FRE', course: 204, title: "Inter French II")
Course.create(subject: 'FRE', course: 341, title: "17th Cent/Class")
Course.create(subject: 'FRE', course: 343, title: "Age/Fr Romance")
Course.create(subject: 'FRE', course: 344, title: "Age/Fr Realism")
Course.create(subject: 'FRE', course: 345, title: "Birth Mod Fr Cul")
Course.create(subject: 'FRE', course: 346, title: "Cont Fr Cult/Art")
Course.create(subject: 'PHI', course: 100, title: "Persp in Philo")
Course.create(subject: 'PHI', course: 115, title: "Logic/Lang")
Course.create(subject: 'PHI', course: 200, title: "World Religions")
Course.create(subject: 'PHI', course: 201, title: "Ancient Philo")
Course.create(subject: 'PHI', course: 206, title: "16th-18th Philo")
Course.create(subject: 'PHI', course: 220, title: "Ethics")
Course.create(subject: 'PHI', course: 305, title: "Medieval Philo")
Course.create(subject: 'PHI', course: 307, title: "Medieval Ethics")
Course.create(subject: 'PHI', course: 308, title: "Bioethics")
Course.create(subject: 'PHI', course: 311, title: "Formal Logic I")
Course.create(subject: 'PHI', course: 312, title: "Formal Logic II")
Course.create(subject: 'PHI', course: 320, title: "Ethical Theory")
Course.create(subject: 'PHI', course: 326, title: "Soc/Polit Philo")
Course.create(subject: 'PHI', course: 355, title: "Philo of Religion")
Course.create(subject: 'PHI', course: 405, title: "Epistemology")
Course.create(subject: 'PHI', course: 410, title: "Metaphysics")
Course.create(subject: 'PHI', course: 415, title: "Philo of Mind")
Course.create(subject: 'PHI', course: 426, title: "Pheno/Existent")
Course.create(subject: 'SPN', course: 101, title: "Elm Spanish I")
Course.create(subject: 'SPN', course: 102, title: "Elm Spanish II")
Course.create(subject: 'SPN', course: 304, title: "Span Law Enf")
Course.create(subject: 'SPN', course: 305, title: "Span Business")
Course.create(subject: 'SPT', course: 305, title: "Ethics in Sport Management")
Course.create(subject: 'WST', course: 200, title: "Intro to Women Studies")
Course.create(subject: 'WST', course: 320, title: "Gay, BiSex, Stud")
Course.create(subject: 'WST', course: 330, title: "Ex Gdr, Rc, Med")
Course.create(subject: 'ART', course: 109, title: "Landmk Wld Art")
Course.create(subject: 'ART', course: 243, title: "Intro Asian Art")
Course.create(subject: 'ART', course: 323, title: "Women in Art")
Course.create(subject: 'ART', course: 326, title: "Contemp Art")
Course.create(subject: 'ART', course: 328, title: "Ital Ren Art")
Course.create(subject: 'COM', course: 275, title: "Art of Film")
Course.create(subject: 'DAN', course: 132, title: "Ballet Tech I")
Course.create(subject: 'DAN', course: 133, title: "Jazz Tech I")
Course.create(subject: 'DAN', course: 232, title: "Ballet Tech I")
Course.create(subject: 'DAN', course: 301, title: "Theater Dan I")
Course.create(subject: 'DAN', course: 302, title: "Theater Dan II")
Course.create(subject: 'GCM', course: 101, title: "Time-Base Med")
Course.create(subject: 'MUS', course: 100, title: "Intro to Music")
Course.create(subject: 'MUS', course: 104, title: "Voice Class")
Course.create(subject: 'MUS', course: 186, title: "Clavinova Ensemble")
Course.create(subject: 'MUS', course: 187, title: "Guitar Ensemble")
Course.create(subject: 'MUS', course: 188, title: "String Ensemble")
Course.create(subject: 'MUS', course: 192, title: "California Sing")
Course.create(subject: 'MUS', course: 193, title: "Univ Gosp Ch")
Course.create(subject: 'MUS', course: 196, title: "Jazz Ensemble")
Course.create(subject: 'MUS', course: 198, title: "Marching Band")
Course.create(subject: 'MUS', course: 199, title: "Concert Band")
Course.create(subject: 'MUS', course: 211, title: "Keyboard I")
Course.create(subject: 'MUS', course: 215, title: "Comp Music I")
Course.create(subject: 'MUS', course: 300, title: "Jazz (Hist/Form)")
Course.create(subject: 'MUS', course: 304, title: "American Musical")
Course.create(subject: 'MUS', course: 305, title: "Carib and Gosip")
Course.create(subject: 'MUS', course: 306, title: "Opera")
Course.create(subject: 'MUS', course: 307, title: "Spec Mus Proj")
Course.create(subject: 'MUS', course: 310, title: "Music in Media")
Course.create(subject: 'MUS', course: 313, title: "Rock N' Roll")
Course.create(subject: 'MUS', course: 315, title: "Comp Mus II")
Course.create(subject: 'MUS', course: 372, title: "Cre Art Elm Ed")
Course.create(subject: 'PHI', course: 335, title: "Aesthetic Theo")
Course.create(subject: 'PHI', course: 336, title: "Philo of Film")
Course.create(subject: 'THE', course: 100, title: "Intro Theat")
Course.create(subject: 'THE', course: 101, title: "Voice/Speech")
Course.create(subject: 'THE', course: 131, title: "Fund of Acting")
Course.create(subject: 'THE', course: 201, title: "Voice/Interpret")
Course.create(subject: 'THE', course: 231, title: "Intermed Acting")
Course.create(subject: 'THE', course: 309, title: "Readers Theat")
Course.create(subject: "BIO", course: 488, title: "Water Pollution Biology", credits: 4)
Course.create(subject: "BIO", course: 307, title: "Plant Anatomy", credits: 4)
Course.create(subject: "BIO", course: 336, title: "Plant Taxonomy", credits: 4)
Course.create(subject: "BIO", course: 407, title: "Mycology", credits: 4)
Course.create(subject: "HON", course: 150, title: "Honors Composition I")
Course.create(subject: "HON", course: 100, title: "Honors and University Orientation")
Course.create(subject: "HON", course: 250, title: "Honors Composition II")
Course.create(subject: "EDE", course: 211, title: "Instructional Strategies in Elementary and Early Childhood Education")




Prerequisites.create(parent_course_id: Course.where(subject: "HON", course: 250).take, prerequisite_course_id: Course.where(subject: "HON", course: 150).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 407).take, prerequisite_course_id: Course.where(subject: "BIO", course: 125).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 407).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 336).take, prerequisite_course_id: Course.where(subject: "BIO", course: 125).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 336).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 307).take, prerequisite_course_id: Course.where(subject: "BIO", course: 125).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 307).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 124).take, prerequisite_course_id: Course.where(subject: "CSC", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 216).take, prerequisite_course_id: Course.where(subject: "MAT", course: 195).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 265).take, prerequisite_course_id: Course.where(subject: "CSC", course: 124).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 323).take, prerequisite_course_id: Course.where(subject: "CSC", course: 328).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 328).take, prerequisite_course_id: Course.where(subject: "CSC", course: 265).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CET", course: 350).take, prerequisite_course_id: Course.where(subject: "CSC", course: 265).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 360).take, prerequisite_course_id: Course.where(subject: "CSC", course: 328).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 378).take, prerequisite_course_id: Course.where(subject: "CSC", course: 323).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 400).take, prerequisite_course_id: Course.where(subject: "CSC", course: 378).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 455).take, prerequisite_course_id: Course.where(subject: "CSC", course: 328).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 460).take, prerequisite_course_id: Course.where(subject: "CSC", course: 475).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 475).take, prerequisite_course_id: Course.where(subject: "CSC", course: 216).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 475).take, prerequisite_course_id: Course.where(subject: "CSC", course: 328).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 490).take, prerequisite_course_id: Course.where(subject: "CSC", course: 265).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 490).take, prerequisite_course_id: Course.where(subject: "ENG", course: 217).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 492).take, prerequisite_course_id: Course.where(subject: "CSC", course: 490).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 302).take, prerequisite_course_id: Course.where(subject: "CSC", course: 265).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 304).take, prerequisite_course_id: Course.where(subject: "CSC", course: 124).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 306).take, prerequisite_course_id: Course.where(subject: "CSC", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 420).take, prerequisite_course_id: Course.where(subject: "CSC", course: 328).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 424).take, prerequisite_course_id: Course.where(subject: "CSC", course: 328).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 424).take, prerequisite_course_id: Course.where(subject: "MAT", course: 282).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CSC", course: 424).take, prerequisite_course_id: Course.where(subject: "MAT", course: 341).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MAT", course: 282).take, prerequisite_course_id: Course.where(subject: "MAT", course: 281).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MAT", course: 341).take, prerequisite_course_id: Course.where(subject: "MAT", course: 195).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 217).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CET", course: 440).take, prerequisite_course_id: Course.where(subject: "CSC", course: 124).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MAT", course: 381).take, prerequisite_course_id: Course.where(subject: "MAT", course: 282).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MAT", course: 441).take, prerequisite_course_id: Course.where(subject: "MAT", course: 341).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MAT", course: 382).take, prerequisite_course_id: Course.where(subject: "MAT", course: 381).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CHE", course: 102).take, prerequisite_course_id: Course.where(subject: "CHE", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "CHE", course: 331).take, prerequisite_course_id: Course.where(subject: "CHE", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHY", course: 101).take, prerequisite_course_id: Course.where(subject: "MAT", course: 281).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHY", course: 202).take, prerequisite_course_id: Course.where(subject: "MAT", course: 282).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHY", course: 202).take, prerequisite_course_id: Course.where(subject: "PHY", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHY", course: 203).take, prerequisite_course_id: Course.where(subject: "PHY", course: 202).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHY", course: 321).take, prerequisite_course_id: Course.where(subject: "PHY", course: 202).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 215).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 215).take, prerequisite_course_id: Course.where(subject: "BIO", course: 125).take.id, course_group_id: 2)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 488).take, prerequisite_course_id: Course.where(subject: "CHE", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 445).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 445).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 248).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 2)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 248).take, prerequisite_course_id: Course.where(subject: "BIO", course: 125).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 248).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 305).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 305).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 306).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 306).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 325).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 325).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 327).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 327).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 328).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 328).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 433).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 433).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 486).take, prerequisite_course_id: Course.where(subject: "BIO", course: 120).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 486).take, prerequisite_course_id: Course.where(subject: "BIO", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "COM", course: 351).take, prerequisite_course_id: Course.where(subject: "COM", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "COM", course: 351).take, prerequisite_course_id: Course.where(subject: "COM", course: 230).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 205).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 205).take, prerequisite_course_id: Course.where(subject: "HON", course: 150).take.id, course_group_id: 2)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 206).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 206).take, prerequisite_course_id: Course.where(subject: "HON", course: 150).take.id, course_group_id: 2)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 102).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 301).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 301).take, prerequisite_course_id: Course.where(subject: "ENG", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 306).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 306).take, prerequisite_course_id: Course.where(subject: "ENG", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 315).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 315).take, prerequisite_course_id: Course.where(subject: "ENG", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 337).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 337).take, prerequisite_course_id: Course.where(subject: "ENG", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 354).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 354).take, prerequisite_course_id: Course.where(subject: "ENG", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 487).take, prerequisite_course_id: Course.where(subject: "ENG", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 487).take, prerequisite_course_id: Course.where(subject: "ENG", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "SPN", course: 304).take, prerequisite_course_id: Course.where(subject: "SPN", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "SPN", course: 304).take, prerequisite_course_id: Course.where(subject: "SPN", course: 102).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "ENG", course: 338).take, prerequisite_course_id: Course.where(subject: "ENG", course: 337).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "FRE", course: 102).take, prerequisite_course_id: Course.where(subject: "FRE", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "FRE", course: 204).take, prerequisite_course_id: Course.where(subject: "FRE", course: 203).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHI", course: 312).take, prerequisite_course_id: Course.where(subject: "PHI", course: 311).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "SPN", course: 102).take, prerequisite_course_id: Course.where(subject: "SPN", course: 101).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "DAN", course: 232).take, prerequisite_course_id: Course.where(subject: "DAN", course: 132).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 305).take, prerequisite_course_id: Course.where(subject: "MUS", course: 100).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 315).take, prerequisite_course_id: Course.where(subject: "MUS", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "PHI", course: 336).take, prerequisite_course_id: Course.where(subject: "PHI", course: 335).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "THE", course: 101).take, prerequisite_course_id: Course.where(subject: "THE", course: 100).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 211).take, prerequisite_course_id: Course.where(subject: "MUS", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 304).take, prerequisite_course_id: Course.where(subject: "MUS", course: 100).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 313).take, prerequisite_course_id: Course.where(subject: "MUS", course: 100).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 315).take, prerequisite_course_id: Course.where(subject: "MUS", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 372).take, prerequisite_course_id: Course.where(subject: "EDE", course: 211).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "THE", course: 231).take, prerequisite_course_id: Course.where(subject: "THE", course: 131).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "THE", course: 309).take, prerequisite_course_id: Course.where(subject: "THE", course: 201).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 306).take, prerequisite_course_id: Course.where(subject: "MUS", course: 100).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "MUS", course: 306).take, prerequisite_course_id: Course.where(subject: "MUS", course: 215).take.id, course_group_id: 1)
Prerequisites.create(parent_course_id: Course.where(subject: "BIO", course: 488).take, prerequisite_course_id: Course.where(subject: "CHE", course: 101).take.id, course_group_id: 1)







DaysTime.create(days: "MWF", start_time: "8:00 am", end_time: "8:50 am")
DaysTime.create(days: "MWF", start_time: "9:00 am", end_time: "9:50 am")
DaysTime.create(days: "MWF", start_time: "10:00 am", end_time: "10:50 am")
DaysTime.create(days: "MWF", start_time: "11:00 am", end_time: "11:50 am")
DaysTime.create(days: "MWF", start_time: "12:00 pm", end_time: "12:50 pm")
DaysTime.create(days: "MWF", start_time: "1:00 pm", end_time: "1:50 pm")
DaysTime.create(days: "MWF", start_time: "2:00 pm", end_time: "2:50 pm")
DaysTime.create(days: "MWF", start_time: "3:00 pm", end_time: "3:50 pm")
DaysTime.create(days: "MWF", start_time: "4:00 pm", end_time: "4:50 pm")
DaysTime.create(days: "MW", start_time: "4:00 pm", end_time: "5:15 pm")
DaysTime.create(days: "TR", start_time: "8:00 am", end_time: "9:15 am")
DaysTime.create(days: "TR", start_time: "9:30 am", end_time: "10:45 am")
DaysTime.create(days: "TR", start_time: "12:30 pm", end_time: "1:45 pm")
DaysTime.create(days: "TR", start_time: "2:00 pm", end_time: "3:15 pm")
DaysTime.create(days: "TR", start_time: "3:30 pm", end_time: "4:45 pm")
DaysTime.create(days: "M", start_time: "6:00 pm", end_time: "8:45 pm")
DaysTime.create(days: "W", start_time: "6:00 pm", end_time: "8:45 pm")
DaysTime.create(days: "W", start_time: "4:00 pm", end_time: "6:50 pm")

WorkDaysTime.create(days: "M", start_time: "8:00am", end_time: "8:30am")
WorkDaysTime.create(days: "M", start_time: "8:30am", end_time: "9:00am")
WorkDaysTime.create(days: "M", start_time: "9:00am", end_time: "9:30am")
WorkDaysTime.create(days: "M", start_time: "9:30am", end_time: "10:00am")
WorkDaysTime.create(days: "M", start_time: "10:00am", end_time: "10:30am")
WorkDaysTime.create(days: "M", start_time: "10:30am", end_time: "11:00am")
WorkDaysTime.create(days: "M", start_time: "11:00am", end_time: "11:30am")
WorkDaysTime.create(days: "M", start_time: "11:30am", end_time: "12:00pm")
WorkDaysTime.create(days: "M", start_time: "12:00pm", end_time: "12:30pm")
WorkDaysTime.create(days: "M", start_time: "12:30pm", end_time: "1:00pm")
WorkDaysTime.create(days: "M", start_time: "1:00pm", end_time: "1:30pm")
WorkDaysTime.create(days: "M", start_time: "1:30pm", end_time: "2:00pm")
WorkDaysTime.create(days: "M", start_time: "2:00pm", end_time: "2:30pm")
WorkDaysTime.create(days: "M", start_time: "2:30pm", end_time: "3:00pm")
WorkDaysTime.create(days: "M", start_time: "3:00pm", end_time: "3:30pm")
WorkDaysTime.create(days: "M", start_time: "3:30pm", end_time: "4:00pm")
WorkDaysTime.create(days: "M", start_time: "4:00pm", end_time: "4:30pm")
WorkDaysTime.create(days: "M", start_time: "4:30pm", end_time: "5:00pm")
WorkDaysTime.create(days: "M", start_time: "5:00pm", end_time: "5:30pm")
WorkDaysTime.create(days: "M", start_time: "5:30pm", end_time: "6:00pm")
WorkDaysTime.create(days: "M", start_time: "6:00pm", end_time: "6:30pm")
WorkDaysTime.create(days: "M", start_time: "6:30pm", end_time: "7:00pm")
WorkDaysTime.create(days: "M", start_time: "7:00pm", end_time: "7:30pm")
WorkDaysTime.create(days: "M", start_time: "7:30pm", end_time: "8:00pm")
WorkDaysTime.create(days: "M", start_time: "8:00pm", end_time: "8:30pm")
WorkDaysTime.create(days: "M", start_time: "8:30pm", end_time: "9:00pm")
WorkDaysTime.create(days: "M", start_time: "9:00pm", end_time: "9:30pm")
WorkDaysTime.create(days: "M", start_time: "9:30pm", end_time: "10:00pm")
WorkDaysTime.create(days: "T", start_time: "8:00am", end_time: "8:30am")
WorkDaysTime.create(days: "T", start_time: "8:30am", end_time: "9:00am")
WorkDaysTime.create(days: "T", start_time: "9:00am", end_time: "9:30am")
WorkDaysTime.create(days: "T", start_time: "9:30am", end_time: "10:00am")
WorkDaysTime.create(days: "T", start_time: "10:00am", end_time: "10:30am")
WorkDaysTime.create(days: "T", start_time: "10:30am", end_time: "11:00am")
WorkDaysTime.create(days: "T", start_time: "11:00am", end_time: "11:30am")
WorkDaysTime.create(days: "T", start_time: "11:30am", end_time: "12:00pm")
WorkDaysTime.create(days: "T", start_time: "12:00pm", end_time: "12:30pm")
WorkDaysTime.create(days: "T", start_time: "12:30pm", end_time: "1:00pm")
WorkDaysTime.create(days: "T", start_time: "1:00pm", end_time: "1:30pm")
WorkDaysTime.create(days: "T", start_time: "1:30pm", end_time: "2:00pm")
WorkDaysTime.create(days: "T", start_time: "2:00pm", end_time: "2:30pm")
WorkDaysTime.create(days: "T", start_time: "2:30pm", end_time: "3:00pm")
WorkDaysTime.create(days: "T", start_time: "3:00pm", end_time: "3:30pm")
WorkDaysTime.create(days: "T", start_time: "3:30pm", end_time: "4:00pm")
WorkDaysTime.create(days: "T", start_time: "4:00pm", end_time: "4:30pm")
WorkDaysTime.create(days: "T", start_time: "4:30pm", end_time: "5:00pm")
WorkDaysTime.create(days: "T", start_time: "5:00pm", end_time: "5:30pm")
WorkDaysTime.create(days: "T", start_time: "5:30pm", end_time: "6:00pm")
WorkDaysTime.create(days: "T", start_time: "6:00pm", end_time: "6:30pm")
WorkDaysTime.create(days: "T", start_time: "6:30pm", end_time: "7:00pm")
WorkDaysTime.create(days: "T", start_time: "7:00pm", end_time: "7:30pm")
WorkDaysTime.create(days: "T", start_time: "7:30pm", end_time: "8:00pm")
WorkDaysTime.create(days: "T", start_time: "8:00pm", end_time: "8:30pm")
WorkDaysTime.create(days: "T", start_time: "8:30pm", end_time: "9:00pm")
WorkDaysTime.create(days: "T", start_time: "9:00pm", end_time: "9:30pm")
WorkDaysTime.create(days: "T", start_time: "9:30pm", end_time: "10:00pm")
WorkDaysTime.create(days: "W", start_time: "8:00am", end_time: "8:30am")
WorkDaysTime.create(days: "W", start_time: "8:30am", end_time: "9:00am")
WorkDaysTime.create(days: "W", start_time: "9:00am", end_time: "9:30am")
WorkDaysTime.create(days: "W", start_time: "9:30am", end_time: "10:00am")
WorkDaysTime.create(days: "W", start_time: "10:00am", end_time: "10:30am")
WorkDaysTime.create(days: "W", start_time: "10:30am", end_time: "11:00am")
WorkDaysTime.create(days: "W", start_time: "11:00am", end_time: "11:30am")
WorkDaysTime.create(days: "W", start_time: "11:30am", end_time: "12:00pm")
WorkDaysTime.create(days: "W", start_time: "12:00pm", end_time: "12:30pm")
WorkDaysTime.create(days: "W", start_time: "12:30pm", end_time: "1:00pm")
WorkDaysTime.create(days: "W", start_time: "1:00pm", end_time: "1:30pm")
WorkDaysTime.create(days: "W", start_time: "1:30pm", end_time: "2:00pm")
WorkDaysTime.create(days: "W", start_time: "2:00pm", end_time: "2:30pm")
WorkDaysTime.create(days: "W", start_time: "2:30pm", end_time: "3:00pm")
WorkDaysTime.create(days: "W", start_time: "3:00pm", end_time: "3:30pm")
WorkDaysTime.create(days: "W", start_time: "3:30pm", end_time: "4:00pm")
WorkDaysTime.create(days: "W", start_time: "4:00pm", end_time: "4:30pm")
WorkDaysTime.create(days: "W", start_time: "4:30pm", end_time: "5:00pm")
WorkDaysTime.create(days: "W", start_time: "5:00pm", end_time: "5:30pm")
WorkDaysTime.create(days: "W", start_time: "5:30pm", end_time: "6:00pm")
WorkDaysTime.create(days: "W", start_time: "6:00pm", end_time: "6:30pm")
WorkDaysTime.create(days: "W", start_time: "6:30pm", end_time: "7:00pm")
WorkDaysTime.create(days: "W", start_time: "7:00pm", end_time: "7:30pm")
WorkDaysTime.create(days: "W", start_time: "7:30pm", end_time: "8:00pm")
WorkDaysTime.create(days: "W", start_time: "8:00pm", end_time: "8:30pm")
WorkDaysTime.create(days: "W", start_time: "8:30pm", end_time: "9:00pm")
WorkDaysTime.create(days: "W", start_time: "9:00pm", end_time: "9:30pm")
WorkDaysTime.create(days: "W", start_time: "9:30pm", end_time: "10:00pm")
WorkDaysTime.create(days: "R", start_time: "8:00am", end_time: "8:30am")
WorkDaysTime.create(days: "R", start_time: "8:30am", end_time: "9:00am")
WorkDaysTime.create(days: "R", start_time: "9:00am", end_time: "9:30am")
WorkDaysTime.create(days: "R", start_time: "9:30am", end_time: "10:00am")
WorkDaysTime.create(days: "R", start_time: "10:00am", end_time: "10:30am")
WorkDaysTime.create(days: "R", start_time: "10:30am", end_time: "11:00am")
WorkDaysTime.create(days: "R", start_time: "11:00am", end_time: "11:30am")
WorkDaysTime.create(days: "R", start_time: "11:30am", end_time: "12:00pm")
WorkDaysTime.create(days: "R", start_time: "12:00pm", end_time: "12:30pm")
WorkDaysTime.create(days: "R", start_time: "12:30pm", end_time: "1:00pm")
WorkDaysTime.create(days: "R", start_time: "1:00pm", end_time: "1:30pm")
WorkDaysTime.create(days: "R", start_time: "1:30pm", end_time: "2:00pm")
WorkDaysTime.create(days: "R", start_time: "2:00pm", end_time: "2:30pm")
WorkDaysTime.create(days: "R", start_time: "2:30pm", end_time: "3:00pm")
WorkDaysTime.create(days: "R", start_time: "3:00pm", end_time: "3:30pm")
WorkDaysTime.create(days: "R", start_time: "3:30pm", end_time: "4:00pm")
WorkDaysTime.create(days: "R", start_time: "4:00pm", end_time: "4:30pm")
WorkDaysTime.create(days: "R", start_time: "4:30pm", end_time: "5:00pm")
WorkDaysTime.create(days: "R", start_time: "5:00pm", end_time: "5:30pm")
WorkDaysTime.create(days: "R", start_time: "5:30pm", end_time: "6:00pm")
WorkDaysTime.create(days: "R", start_time: "6:00pm", end_time: "6:30pm")
WorkDaysTime.create(days: "R", start_time: "6:30pm", end_time: "7:00pm")
WorkDaysTime.create(days: "R", start_time: "7:00pm", end_time: "7:30pm")
WorkDaysTime.create(days: "R", start_time: "7:30pm", end_time: "8:00pm")
WorkDaysTime.create(days: "R", start_time: "8:00pm", end_time: "8:30pm")
WorkDaysTime.create(days: "R", start_time: "8:30pm", end_time: "9:00pm")
WorkDaysTime.create(days: "R", start_time: "9:00pm", end_time: "9:30pm")
WorkDaysTime.create(days: "R", start_time: "9:30pm", end_time: "10:00pm")
WorkDaysTime.create(days: "F", start_time: "8:00am", end_time: "8:30am")
WorkDaysTime.create(days: "F", start_time: "8:30am", end_time: "9:00am")
WorkDaysTime.create(days: "F", start_time: "9:00am", end_time: "9:30am")
WorkDaysTime.create(days: "F", start_time: "9:30am", end_time: "10:00am")
WorkDaysTime.create(days: "F", start_time: "10:00am", end_time: "10:30am")
WorkDaysTime.create(days: "F", start_time: "10:30am", end_time: "11:00am")
WorkDaysTime.create(days: "F", start_time: "11:00am", end_time: "11:30am")
WorkDaysTime.create(days: "F", start_time: "11:30am", end_time: "12:00pm")
WorkDaysTime.create(days: "F", start_time: "12:00pm", end_time: "12:30pm")
WorkDaysTime.create(days: "F", start_time: "12:30pm", end_time: "1:00pm")
WorkDaysTime.create(days: "F", start_time: "1:00pm", end_time: "1:30pm")
WorkDaysTime.create(days: "F", start_time: "1:30pm", end_time: "2:00pm")
WorkDaysTime.create(days: "F", start_time: "2:00pm", end_time: "2:30pm")
WorkDaysTime.create(days: "F", start_time: "2:30pm", end_time: "3:00pm")
WorkDaysTime.create(days: "F", start_time: "3:00pm", end_time: "3:30pm")
WorkDaysTime.create(days: "F", start_time: "3:30pm", end_time: "4:00pm")
WorkDaysTime.create(days: "F", start_time: "4:00pm", end_time: "4:30pm")
WorkDaysTime.create(days: "F", start_time: "4:30pm", end_time: "5:00pm")
WorkDaysTime.create(days: "F", start_time: "5:00pm", end_time: "5:30pm")
WorkDaysTime.create(days: "F", start_time: "5:30pm", end_time: "6:00pm")
WorkDaysTime.create(days: "F", start_time: "6:00pm", end_time: "6:30pm")
WorkDaysTime.create(days: "F", start_time: "6:30pm", end_time: "7:00pm")
WorkDaysTime.create(days: "F", start_time: "7:00pm", end_time: "7:30pm")
WorkDaysTime.create(days: "F", start_time: "7:30pm", end_time: "8:00pm")
WorkDaysTime.create(days: "F", start_time: "8:00pm", end_time: "8:30pm")
WorkDaysTime.create(days: "F", start_time: "8:30pm", end_time: "9:00pm")
WorkDaysTime.create(days: "F", start_time: "9:00pm", end_time: "9:30pm")
WorkDaysTime.create(days: "F", start_time: "9:30pm", end_time: "10:00pm")

Semester.create(semester: "Fall 2014")
Semester.create(semester: "Spring 2015", active: true)
Semester.create(semester: "Fall 2015")
Semester.create(semester: "Spring 2016")
Semester.create(semester: "Fall 2016")
Semester.create(semester: "Spring 2017")

Major.create(major: "Computer Science")
Major.create(major: "Mathematics")
Major.create(major: "Computer Engineering Technology")
Major.create(major: "Chemistry")
Major.create(major: "Computer Information Systems")

CurriculumCategory.create!([
  {category: "Core", major_id: 1, minor: false},
  {category: "Values", major_id: 1, minor: false},
  {category: "Electives", major_id: 1, minor: false},
  {category: "Critical Thinking Skills", major_id: 1, minor: false},
  {category: "Technological Literacy", major_id: 1, minor: false},
  {category: "Building a Sense of Community", major_id: 1, minor: false},
  {category: "Communication Skills", major_id: 1, minor: false},
  {category: "Mathematics", major_id: 1, minor: false},
  {category: "Natural Sciences", major_id: 1, minor: false},
  {category: "Social Sciences", major_id: 1, minor: false},
  {category: "Humanities", major_id: 1, minor: false},
  {category: "Fine Arts", major_id: 1, minor: false},
  {category: "Multiculutual Awareness", major_id: 1, minor: false},
  {category: "Health and Wellness", major_id: 1, minor: false},
  {category: "Required", major_id: 1, minor: true},
  {category: "Electives", major_id: 1, minor: true},
  {category: "Required", major_id: 2, minor: true},
  {category: "Electives", major_id: 2, minor: true}
])



User.create(first_name: "Anthony", last_name: "Pyzdrowski", email: "pyzdrowski@calu.edu", advisor: true, password: 'password!!15', password_confirmation: 'password!!15', major_id: 1)
User.create(first_name: "Weifeng", last_name: "Chen", email: "chen@calu.edu", advisor: true, password: 'password!!15', password_confirmation: 'password!!15', major_id: 1)
User.create(first_name: "Paul", last_name: "Sible", email: "sible@calu.edu", advisor: true, password: 'password!!15', password_confirmation: 'password!!15', major_id: 1)
User.create(first_name: "Jeffrey", last_name: "Sumey", email: "sumey@calu.edu", advisor: true, password: 'password!!15', password_confirmation: 'password!!15', major_id: 3)
User.create(first_name: "Ghassan", last_name: "Salim", email: "salim@calu.edu", advisor: true, password: 'password!!15', password_confirmation: 'password!!15', major_id: 3)
User.create(first_name: "Gary", last_name: "DeLorenzo", email: "delorenzo@calu.edu", advisor: true, password: "password!!15", password_confirmation: "password!!15", major_id: 3)
